'use client'
import {useEffect,useState} from 'react'
import {ManagedForm,useManagedActionState,useUnsavedForms} from '@/components/admin/ManagedForm'
import {manageClubOfferAction} from '@/app/admin/venue/actions'
import {EMPTY_VENUE_STATE} from '@/app/admin/venue/state'
import {PersianExpiryField} from './PersianExpiryField'
import styles from './CustomerClubPanel.module.css'
type Row={id?:number;userId?:string;name?:string;phone?:string|null;title?:string;description?:string|null;discountLabel?:string;active?:boolean;expiresAt?:string|null;issued?:number;code?:string;status?:string}
function OfferEditor({offer,placeId}:{offer:Row;placeId:number}){
 const [state,action,pending]=useManagedActionState(manageClubOfferAction,EMPTY_VENUE_STATE)
 return <ManagedForm action={action} onSubmit={event=>{if((event.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='cancel'&&!window.confirm('پیشنهاد متوقف و تمام کدهای مصرف‌نشده لغو شوند؟'))event.preventDefault()}}><input name="placeId" type="hidden" value={placeId}/><input name="offerId" type="hidden" value={offer.id}/><strong>{offer.title}</strong><p>{offer.active===false?'متوقف‌شده':offer.expiresAt&&new Date(offer.expiresAt)<=new Date()?'منقضی':'فعال'} · {Number(offer.issued??0).toLocaleString('fa-IR')} کد صادرشده</p>{Number(offer.issued??0)===0&&offer.active!==false&&<><label>عنوان<input name="title" defaultValue={offer.title} required maxLength={120}/></label><label>مقدار تخفیف<input name="discountLabel" defaultValue={offer.discountLabel} required maxLength={80}/></label><label>شرایط<textarea name="description" defaultValue={offer.description??''} maxLength={500}/></label><PersianExpiryField defaultValue={offer.expiresAt}/><button name="operation" value="edit" disabled={pending}>ذخیره پیشنهاد</button></>}{offer.active!==false&&<button name="operation" value="cancel" formNoValidate disabled={pending}>توقف پیشنهاد و کدها</button>}{(state.error||state.message)&&<p role={state.ok?'status':'alert'} className={state.ok?styles.ok:styles.error}>{state.error||state.message}</p>}</ManagedForm>
}
export function ClubHistory({placeId,onMembers}:{placeId:number;onMembers:(rows:{userId:string;name:string;phone:string|null;joinedAt:Date}[])=>void}){
 const draft=useUnsavedForms()
 const leave=()=>draft.confirmDiscard()
 const [rows,setRows]=useState<Row[]>([]),[section,setSection]=useState<'members'|'offers'|'codes'>('members'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0)
 useEffect(()=>{const reload=(event:Event)=>{if((event as CustomEvent).detail.ok)setVersion(value=>value+1)};document.addEventListener('managed-form-result',reload);return()=>document.removeEventListener('managed-form-result',reload)},[])
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/admin/club?place=${placeId}&section=${section}&q=${encodeURIComponent(query)}&page=${page}`,{signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);if(controller.signal.aborted)return;setRows(data.rows);setTotal(data.total);if(data.page!==page)setPage(data.page);if(section==='members')onMembers(data.rows)}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'اطلاعات دریافت نشد.')}finally{if(!controller.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);controller.abort()}},[placeId,section,query,page,version,onMembers])
 const statuses:Record<string,string>={issued:'قابل استفاده',redeemed:'مصرف‌شده',cancelled:'لغوشده',expired:'منقضی'}
 return <div ref={draft.root} onInputCapture={draft.mark} onChangeCapture={draft.mark} className={styles.history}><h3>اعضا، پیشنهادها و تاریخچه کدها</h3><div className={styles.tabs}>{(['members','offers','codes'] as const).map(value=><button key={value} type="button" aria-pressed={section===value} onClick={()=>{if(leave()){setSection(value);setPage(1)}}}>{{members:'اعضا',offers:'مدیریت پیشنهادها',codes:'تاریخچه کدها'}[value]}</button>)}</div>{section==='members'&&<label>جست‌وجوی نام یا شماره عضو<input value={query} onChange={event=>{if(leave()){setQuery(event.target.value);setPage(1)}}} maxLength={120}/></label>}{error&&<p role="alert" className={styles.error}>{error}<button onClick={()=>setVersion(value=>value+1)}>تلاش دوباره</button></p>}
 <div className={section==='offers'?styles.grid:styles.members} aria-busy={loading}>{!loading&&!rows.length&&<p>رکوردی وجود ندارد.</p>}{section==='members'&&rows.map(row=><span key={row.userId}><b>{row.name||'بدون نام'}</b><a dir="ltr" href={row.phone?`tel:${row.phone}`:undefined}>{row.phone??'شماره ثبت نشده'}</a></span>)}{section==='offers'&&rows.map(offer=><OfferEditor key={offer.id} offer={offer} placeId={placeId}/>)}{section==='codes'&&rows.map(row=><span key={row.id}><b>{row.name} · {row.title}</b><code dir="ltr">{row.code}</code><small>{statuses[row.status??'']??row.status}</small></span>)}</div><div className={styles.tabs}><button disabled={loading||page===1} onClick={()=>{if(leave())setPage(value=>value-1)}}>قبلی</button><span role="status">{loading?'در حال دریافت…':`${total.toLocaleString('fa-IR')} رکورد · صفحه ${page.toLocaleString('fa-IR')}`}</span><button disabled={loading||page*25>=total} onClick={()=>{if(leave())setPage(value=>value+1)}}>بعدی</button></div></div>
}
