'use client'
import {useEffect,useState} from 'react'
import {ManagedForm,useManagedActionState} from './ManagedForm'
import {restoreBulkPriceAction} from '@/app/admin/venue/actions'
import {EMPTY_VENUE_STATE} from '@/app/admin/venue/state'
import styles from './AdminDashboard.module.css'
type Row={id:number;actorLabel:string;action:string;entity:string;entityId:string;createdAt:string;canRestore:boolean;itemCount:number|null}
const labels:Record<string,string>={'menu.bulk_price':'تغییر گروهی قیمت','menu.bulk_price.restore':'بازگردانی قیمت','place.archive':'آرشیو کافه','place.restore':'بازیابی کافه','place.update':'ویرایش اطلاعات','place.hours':'تنظیم ساعت کاری','place.attributes':'ویرایش امکانات','place.status':'تغییر وضعیت','menu_item.update':'ویرایش آیتم','menu_section.scope':'تعیین مالکیت دسته'}
const entities:Record<string,string>={place:'مجموعه',menu_item:'آیتم منو',menu_section:'دسته منو',review:'نظر',app_user:'کاربر',user:'کاربر',club_offer:'پیشنهاد باشگاه'}
function HistoryRow({row,placeId,revision}:{row:Row;placeId?:number;revision?:string}){
 const [state,restore,pending]=useManagedActionState(restoreBulkPriceAction,EMPTY_VENUE_STATE)
 const [details,setDetails]=useState(''),[error,setError]=useState('')
 return <li className={styles.rowCard} style={{display:'grid',gap:10}}><strong>{labels[row.action]??row.action}</strong><span>{entities[row.entity]??row.entity} · شناسه <bdi>{row.entityId}</bdi></span><span>{row.actorLabel||'سیستم'} · {new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(new Date(row.createdAt))}</span>{row.itemCount!=null&&<span>{Number(row.itemCount).toLocaleString('fa-IR')} آیتم</span>}<button type="button" className={styles.btnGhost} onClick={async()=>{if(details){setDetails('');return}try{const response=await fetch(`/api/admin/history?id=${row.id}${placeId?`&place=${placeId}`:''}`,{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();setDetails(JSON.stringify(data.details,null,2));setError('')}catch{setError('جزئیات دریافت نشد؛ دوباره تلاش کنید.')}}}>جزئیات عملیات</button>{details&&<pre dir="ltr" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:320,overflow:'auto',fontSize:12}}>{details}</pre>}{error&&<p role="alert">{error}</p>}{placeId&&revision&&row.canRestore&&<ManagedForm action={restore} onSubmit={event=>{if(!window.confirm('قیمت‌های پیش از این عملیات بازگردانده شوند؟ اگر قیمت دوباره تغییر کرده باشد، عملیات انجام نمی‌شود.'))event.preventDefault()}}><input name="placeId" value={placeId} type="hidden"/><input name="revision" value={revision} type="hidden"/><input name="auditId" value={row.id} type="hidden"/><button className={styles.btnGhost} disabled={pending}>{pending?'در حال بررسی…':'بازگردانی این تغییر قیمت'}</button>{(state.error||state.message)&&<p role={state.ok?'status':'alert'}>{state.error||state.message}</p>}</ManagedForm>}</li>
}
export function AuditHistory({placeId,revision}:{placeId?:number;revision?:string}){
 const [rows,setRows]=useState<Row[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[action,setAction]=useState(''),[version,setVersion]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 useEffect(()=>{const changed=(event:Event)=>{if((event as CustomEvent).detail.ok)setVersion(value=>value+1)};document.addEventListener('managed-form-result',changed);return()=>document.removeEventListener('managed-form-result',changed)},[])
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/admin/history?page=${page}&action=${encodeURIComponent(action)}${placeId?`&place=${placeId}`:''}`,{cache:'no-store',signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setRows(data.rows);setTotal(data.total);if(data.page!==page)setPage(data.page)}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'تاریخچه دریافت نشد.')}finally{if(!controller.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);controller.abort()}},[placeId,page,action,version])
 return <section className={styles.section}><h2 className={styles.h2}>تاریخچه عملیات</h2><label>نوع عملیات<select className={styles.select} value={action} onChange={event=>{setAction(event.target.value);setPage(1)}}><option value="">همه</option><option value="menu.bulk_price">قیمت‌ها و بازگردانی</option><option value="place.">اطلاعات کافه</option><option value="menu_">منو</option><option value="club.">باشگاه</option><option value="review.">نظر و پاسخ</option><option value="topmenu">اسکرپ</option></select></label>{error&&<p role="alert" className={styles.error}>{error}<button onClick={()=>setVersion(value=>value+1)}>تلاش دوباره</button></p>}<ul className={styles.list} aria-busy={loading}>{rows.map(row=><HistoryRow key={row.id} row={row} placeId={placeId} revision={revision}/>)}{!rows.length&&!loading&&<li>هنوز عملیاتی ثبت نشده است.</li>}</ul><div className={styles.catalogPagination}><button disabled={loading||page<=1} onClick={()=>setPage(value=>value-1)}>قبلی</button><span role="status">{loading?'در حال دریافت…':`${total.toLocaleString('fa-IR')} عملیات · صفحه ${page.toLocaleString('fa-IR')}`}</span><button disabled={loading||page*25>=total} onClick={()=>setPage(value=>value+1)}>بعدی</button></div></section>
}
